name = "module-worker"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-28"

[build.upload]
format = "modules"
dir = "./dist"
main = "./index.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[build]
command = "npm run -s build"
